# Snaps cannot be built inside docker containers since snap requires systemd

services:
  rust-gtk-appimage:
    build:
      dockerfile: ./appimage.Dockerfile
    volumes:
      - ../:/mnt:z
#    command: /bin/bash -c "cargo appimage"
#    command: /bin/bash -c "appimage --features adwaita"
    command: tail -f /dev/null

  rust-gtk-win:
    build:
      dockerfile: ./win.Dockerfile
    volumes:
      - ../:/mnt:z
    command: tail -f /dev/null
#    command: cargo build --target x86_64-pc-windows-gnu