name: samrewritten
version: '1.0'
summary: A Steam achievements and stats manager
description: |
  xsv is a command line program for indexing,
  slicing, analyzing, splitting and joining CSV
  files. Commands should be simple, fast and
  composable:
  - Simple tasks should be easy.
  - Performance trade offs should be exposed
    in the CLI interface.
  - Composition should not come at the
    expense of performance.
confinement: devmode
base: core24
parts:
  samrewritten:
    plugin: rust
    source: https://github.com/PaulCombal/samrewritten-2-wip.git

apps:
  samrewritten:
    command: target/release/Sam2